version: '3'
services:
  wsgi-server:
    build:
      context: .
      target: wsgi-server
    environment:
      APP_DOMAIN: localhost:9000,chatgpt-admin.tcanationals.com,chatgpt.tcanationals.com
      WORKER_TIMEOUT: 180
      DJANGO_SUPERUSER_USERNAME: admin # default superuser name
      DJANGO_SUPERUSER_PASSWORD: password # default superuser password
      DJANGO_SUPERUSER_EMAIL: admin@example.com # default superuser email
      ACCOUNT_EMAIL_VERIFICATION: ${ACCOUNT_EMAIL_VERIFICATION:-none} # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
      DB_URL: ${DB_URL:-sqlite:////db/db.sqlite3}
    ports:
      - '8000:8000'
    network_mode: host
    volumes:
      - ./db:/db:rw
  web-server:
    build:
      context: .
    environment:
      - BACKEND_URL=http://localhost:8000
    ports:
      - '9000:9000'
    depends_on:
      - wsgi-server
    network_mode: host

